sudo: required
services:
  - docker

before_install:
  - docker build -t elotgamu/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run elotgamu/react-test npm run test -- --watchAll=false

after_success:
  # Build production images
  - docker build -t elotgamu/react-fibonacci-client ./client
  - docker build -t elotgamu/nginx-fibonacci-server ./nginx
  - docker build -t elotgamu/express-fibonacci-app ./server
  - docker build -t elotgamu/db-fibonacci ./worker
  # Log in to the docker hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take the images and push them to docker hub
  - docker push elotgamu/react-fibonacci-client
  - docker push elotgamu/nginx-fibonacci-server
  - docker push elotgamu/express-fibonacci-app
  - docker push elotgamu/db-fibonacci
